/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nyiit_heatbeatdetection_detector_HeartBeatDetector */

#ifndef _Included_com_nyiit_heatbeatdetection_detector_HeartBeatDetector
#define _Included_com_nyiit_heatbeatdetection_detector_HeartBeatDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nyiit_heatbeatdetection_detector_HeartBeatDetector
 * Method:    detectHeartBeat
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_nyiit_heatbeatdetection_detector_HeartBeatDetector_detectHeartBeat
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
